### PR TITLE
Feature: Introduce search_repo_description flag

### PR DESCRIPTION
**Pull request by engin**
### Changes Proposed:

- Added an optional `search_repo_description` flag to enable filtering of results based on the repository description.
- Bumped the version to v1.3.

### Motivation:

This pull request introduces the `search_repo_description` flag to enhance the functionality of the Alfred-GitHub-Star workflow. With this optional flag, users can now filter search results based on the repository description, providing a more refined and tailored experience. Additionally, the version has been bumped to `v1.3` to signify the inclusion of this feature.

### Screenshots:
Screenshot 2024-03-09 at 23 57 38
Screenshot 2024-03-10 at 00 04 17

### CODE REVIEW

**Comment by yinan-c** [comment]
Thanks for your PR!

**Comment by vitorgalvao** [comment]
Seeing as this is a yes/no option, the correct configuration for it is a Checkbox (which sets the variable to a `0` or `1`), not a freeform Text Field.

**Comment by yinan-c** [comment]
Hi @vitorgalvao , I've added another commit to make it a check box. Ans it is in the latest release.

**Comment by vitorgalvao** [comment]
Oh, I see it. Thumbs up. Already live in the Gallery.

**Pull request merged**
